run:
	curl -s -X POST http://52.66.189.213:8090/irdrop -F 'fileX=@nodeRMap.txt' -F 'fileY=@nodeCurrentMap.txt' -F 'fileZ=@voltageSources.txt' -F 'token=demo'


display:
	perl nodeLocDisplay.pl  -nodeMapLocFile nodeLoc.txt -resultFile IR.res	
